# Generated by Django 2.2.19 on 2023-04-26 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите название ингредиента', max_length=200, unique=True, verbose_name='название ингредиента')),
                ('measurement_unit', models.CharField(help_text='укажите единицы измерения ингредиента', max_length=200, unique=True, verbose_name='единицы измерения ингредиента')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите название тега', max_length=200, unique=True, verbose_name='название тега')),
                ('color', models.CharField(help_text='укажите цветовой HEX-код тега', max_length=10, unique=True, verbose_name='цветовой HEX-код тега')),
                ('slug', models.SlugField(help_text='укажите текстовый идентификатор тега', unique=True, verbose_name='текстовый идентификатор тега')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите название рецепта', max_length=200, verbose_name='название рецепта')),
                ('image', models.ImageField(help_text='добавьте изображение', upload_to='recipes/', verbose_name='изображение')),
                ('text', models.TextField(help_text='введите текст', verbose_name='текст')),
                ('cooking_time', models.IntegerField(help_text='укажите время приготовления в минутах', verbose_name='время приготовления в минутах')),
                ('author', models.ForeignKey(help_text='укажите автора', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredients')),
                ('tags', models.ManyToManyField(to='recipes.Tags')),
            ],
        ),
    ]
