# Generated by Django 4.2 on 2023-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите название ингредиента', max_length=200, unique=True, verbose_name='название ингредиента')),
                ('measurement_unit', models.CharField(help_text='укажите единицы измерения ингредиента', max_length=200, verbose_name='единицы измерения ингредиента')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите название рецепта', max_length=200, verbose_name='название рецепта')),
                ('image', models.ImageField(help_text='добавьте изображение', upload_to='recipes/', verbose_name='изображение')),
                ('text', models.TextField(help_text='введите текст', verbose_name='текст')),
                ('cooking_time', models.IntegerField(help_text='укажите время приготовления в минутах', verbose_name='время приготовления в минутах')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите название тега', max_length=200, unique=True, verbose_name='название тега')),
                ('color', models.CharField(help_text='укажите цветовой HEX-код тега', max_length=10, unique=True, verbose_name='цветовой HEX-код тега')),
                ('slug', models.SlugField(help_text='укажите текстовый идентификатор тега', unique=True, verbose_name='текстовый идентификатор тега')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
    ]
