# Generated by Django 4.2 on 2023-05-07 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='значение должно быть больше 1')], verbose_name='количество')),
                ('ingredient', models.ForeignKey(help_text='укажите ингредиент', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipes.ingredient', verbose_name='ингредиент')),
                ('recipe', models.ForeignKey(help_text='укажите рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipes.recipe', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'Количсетво ингредиента в рецепте',
                'verbose_name_plural': 'Количсетво ингредиента в рецепте',
            },
        ),
        migrations.DeleteModel(
            name='IngredientRecipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='выберите ингредиенты', through='recipes.IngredientAmount', to='recipes.ingredient', verbose_name='ингредиенты'),
        ),
    ]
