# Generated by Django 4.2 on 2023-05-11 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "избранное",
                "verbose_name_plural": "избранное",
                "default_related_name": "favorite",
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="укажите название ингредиента",
                        max_length=200,
                        verbose_name="название ингредиента",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        help_text="укажите единицы измерения ингредиента",
                        max_length=200,
                        verbose_name="единицы измерения ингредиента",
                    ),
                ),
            ],
            options={
                "verbose_name": "ингредиент",
                "verbose_name_plural": "ингредиенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IngredientAmount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="значение должно быть больше 1"
                            )
                        ],
                        verbose_name="количество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Количеcтво ингредиента в рецепте",
                "verbose_name_plural": "Количеcтво ингредиента в рецепте",
                "default_related_name": "ingredient_amount",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="укажите название рецепта",
                        max_length=200,
                        verbose_name="название рецепта",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="добавьте изображение",
                        upload_to="recipes/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="введите текстовое описание",
                        verbose_name="текстовое описание",
                    ),
                ),
                (
                    "cooking_time",
                    models.IntegerField(
                        help_text="укажите время приготовления (в минутах)",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="значение должно быть больше 1"
                            )
                        ],
                        verbose_name="время приготовления (в минутах)",
                    ),
                ),
            ],
            options={
                "verbose_name": "рецепт",
                "verbose_name_plural": "рецепты",
                "default_related_name": "recipes",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="укажите название тега",
                        max_length=200,
                        unique=True,
                        verbose_name="название тега",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="укажите цветовой HEX-код тега",
                        max_length=7,
                        unique=True,
                        verbose_name="цветовой HEX-код тега",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="укажите текстовый идентификатор тега",
                        max_length=200,
                        unique=True,
                        verbose_name="текстовый идентификатор тега",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="укажите рецепт для списка покупок",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.recipe",
                        verbose_name="рецепт",
                    ),
                ),
            ],
            options={
                "verbose_name": "список покупок",
                "verbose_name_plural": "список покупок",
                "default_related_name": "shopping_cart",
            },
        ),
    ]
