# Generated by Django 4.2 on 2023-05-07 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(
                help_text='укажите пользователя',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(
                help_text='укажите автора',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='автор',
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                help_text='выберите ингредиенты',
                through='recipes.IngredientAmount',
                to='recipes.ingredient',
                verbose_name='ингредиенты',
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(
                help_text='выберите теги',
                to='recipes.tag',
                verbose_name='теги',
            ),
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(
                help_text='укажите ингредиент',
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.ingredient',
                verbose_name='ингредиент',
            ),
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(
                help_text='укажите рецепт',
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.recipe',
                verbose_name='рецепт',
            ),
        ),
        migrations.AddField(
            model_name='favourites',
            name='recipe',
            field=models.ForeignKey(
                help_text='укажите рецепт для избранного',
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.recipe',
                verbose_name='рецепт',
            ),
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(
                help_text='укажите пользователя',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
    ]
